FROM builder-image:latest

COPY atomic-reactor/ /opt/atomic-reactor
WORKDIR /opt/atomic-reactor

ARG PIP_FIND_LINKS
ARG PIP_NO_INDEX

# can't build cryptography with Rust
RUN export CRYPTOGRAPHY_DONT_BUILD_RUST=1 \
    && python3.8 -m pip install -U pip setuptools wheel \
    && python3.8 -m pip install -r requirements-build.txt \
    && python3.8 -m pip install -r requirements.txt --no-build-isolation \
    && python3.8 setup.py install

CMD ["python3.8", "-m", "atomic_reactor.cli.main", "--help"]
